#!/usr/bin/env bash
# Installs nginx server on sever

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"

sudo mkdir -p /var/www/html
sudo chown -R "$USER":"$USER" /var/www/html
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404_not_found.html

echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	add_header X-Served-By $HOSTNAME;

	error_page 404 /404_not_found.html;
	location /404 {
		root /var/www/html;
		internal;
	}

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}" | sudo tee /etc/nginx/sites-available/default

sudo service nginx restart
