#!/usr/bin/env bash
# Configures an Nginx server

apt-get update
apt-get install -y nginx

mkdir -p /var/www/html
touch /var/www/html/index.html
echo "Hello World" > /var/www/html/index.html
touch "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html
echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	add_header X-Served-By $HOSTNAME;
	root /var/www/html;
	index index.html;
	location /redirect_me {
		return 301 http://www.youtube.com/watch?v=QH2-TGUlwu4;	
	}
	error_page 404 /404.html;
	location = /404.html{
	internal;
	}
}" > default

sudo mv -f default /etc/nginx/sites-available/default
sudo service nginx restart
