#!/usr/bin/env bash
# Install and configure HAproxy

sudo apt-get -y update
sudo apt-get install -y haproxy
config=\
"
frontend web-frontend
	bind *:80
	mode http
	default_backend web-backend
backend web-backend
	balance roundrobin
	server 54904-web-01 54.237.105.147:80 check
	server 54904-web-02 34.207.237.123:80 check
"
echo "$config" | sdo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
