#!/usr/bin/env bash
# Install and configure HAproxy

sudo apt-get -y update
sudo apt-get install -y haproxy
config=\
"
frontend web_air_bnb_front
	bind *:80
	mode http
	default_backend web-backend


backend web_air_bnb_backend
	mode http
	balance roundrobin
	server 52368-web-01 100.26.236.240:80 check
	server 52368-web-02 34.207.237.123:80 check
"
echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
