#!/usr/bin/env bash
# Displays the content of the file /etc/passwd
# Only displays username, userid ans home directory of the user

while IFS= read -r line
do
	echo "$line" | cut -d ':' -f1,3,6
done < "/etc/passwd"
