#!/usr/bin/env bash
# Displays "Best School" 10 times, but for the 9th iteration,
#+ displays "Best School" and then "Hi" on a new line

num=1
while [ $num -le 10 ]
do
	echo "Best School"
	if [ $num -eq 9 ]
	then
		echo Hi
	fi
	(( num+=1 ))
done
