#!/usr/bin/env bash
# Loops from 1 to 10 and:
#	- displays bad luck for the 4th loop iteration
#	- displays good luck for the 8th loop iteration
#	- displays Best School for the other iterations


for (( i=1; i<=10; i++))
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
