#!/usr/bin/env bash
# Displays:
#+	The content of the current directory
#+	In a list format
#+	If a file or directory starts with 10, it cuts it out of the name
# With for loop
# hidden files are not displayed


command=$(ls)
for file in $command
do
	echo "$file" | cut -d "-" -f 2
done
