#!/usr/bin/env bash
# bash scripts configures an Ubuntu server with the below requirements:
#	loccalhost resolves to 127.0.0.2
#	facebook.com rexoves a to 8.8.8.8

cp /etc/hosts ~/hosts
echo "127.0.0.2		localhost" > ~/hosts
echo "8.8.8.8		facebook.com" >> ~/hosts
cp -f ~/hosts /etc/hosts
